name: 'Johnny Action'
description: 'test something'
inputs:
  name:  # id of input
    description: 'The name of something'
    required: true
    default: 'Johnny'
outputs:
  time: # id of output
    description: 'The time it ran'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
